from typing import Any, Generator

import pyarrow as pa
from cloudquery.sdk.scheduler import TableResolver
from cloudquery.sdk.schema import Column
from cloudquery.sdk.schema import Table
from cloudquery.sdk.schema.resource import Resource
from cloudquery.sdk.types import JSONType

from plugin.client import Client


class Observations(Table):
    def __init__(self) -> None:
        '''
    {
      "quality_grade": "research",
      "time_observed_at": "2021-03-23T07:43:00-04:00",
      "taxon_geoprivacy": "open",
      "annotations": [],
      "uuid": "2a4ed468-d887-4ea7-8269-db2d71737dc5",
      "observed_on_details": {
        "date": "2021-03-23",
        "day": 23,
        "month": 3,
        "year": 2021,
        "hour": 7,
        "week": 12
      },
      "id": 199925657,
      "cached_votes_total": 0,
      "identifications_most_agree": true,
      "created_at_details": {
        "date": "2024-02-20",
        "day": 20,
        "month": 2,
        "year": 2024,
        "hour": 15,
        "week": 8
      },
      "species_guess": "Osprey",
      "identifications_most_disagree": false,
      "tags": [],
      "positional_accuracy": 488,
      "comments_count": 0,
      "site_id": 1,
      "created_time_zone": "America/New_York",
      "license_code": "cc-by-nc",
      "observed_time_zone": "America/New_York",
      "quality_metrics": [],
      "public_positional_accuracy": 488,
      "reviewed_by": [1113591, 4072918, 7637579],
      "oauth_application_id": null,
      "flags": [],
      "created_at": "2024-02-20T15:09:31-05:00",
      "description": null,
      "time_zone_offset": "-05:00",
      "project_ids_with_curator_id": [],
      "observed_on": "2021-03-23",
      "observed_on_string": "2021/03/23 7:43 AM",
      "updated_at": "2024-02-20T17:00:15-05:00",
      "sounds": [],
      "place_ids": [
        1, 30, 921, 9853, 51894, 52250, 59613, 61551, 63888, 66741, 81418,
        82256, 82257, 82529, 90754, 97394, 111970, 117815, 118770, 120540,
        121740, 124285, 127683, 127684, 136508, 156225, 164522
      ],
      "captive": false,
      "taxon": {
        "is_active": true,
        "ancestry": "48460/1/2/355675/3/71261/200958/71725",
        "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
        "endemic": false,
        "iconic_taxon_id": 3,
        "min_species_taxon_id": 116999,
        "threatened": false,
        "rank_level": 10,
        "introduced": false,
        "native": true,
        "parent_id": 71725,
        "name": "Pandion haliaetus",
        "rank": "species",
        "extinct": false,
        "id": 116999,
        "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999],
        "created_at": "2011-08-10T18:24:12+00:00",
        "default_photo": {
          "id": 6903515,
          "license_code": "cc-by-nc",
          "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
          "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
          "original_dimensions": { "height": 1366, "width": 2048 },
          "flags": [],
          "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
          "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
        },
        "taxon_changes_count": 0,
        "taxon_schemes_count": 9,
        "observations_count": 114414,
        "photos_locked": false,
        "universal_search_rank": 114414,
        "flag_counts": { "resolved": 4, "unresolved": 0 },
        "current_synonymous_taxon_ids": null,
        "atlas_id": null,
        "complete_species_count": null,
        "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
        "complete_rank": "subspecies",
        "iconic_taxon_name": "Aves",
        "preferred_common_name": "Osprey"
      },
      "ident_taxon_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999],
      "outlinks": [],
      "faves_count": 0,
      "ofvs": [],
      "num_identification_agreements": 2,
      "preferences": { "prefers_community_taxon": null },
      "comments": [],
      "map_scale": null,
      "uri": "https://www.inaturalist.org/observations/199925657",
      "project_ids": [],
      "community_taxon_id": 116999,
      "geojson": {
        "type": "Point",
        "coordinates": [-79.0673273798, 35.6496553353]
      },
      "owners_identification_from_vision": true,
      "identifications_count": 2,
      "obscured": false,
      "num_identification_disagreements": 0,
      "geoprivacy": null,
      "location": "35.6496553353,-79.0673273798",
      "votes": [],
      "spam": false,
      "mappable": true,
      "identifications_some_agree": true,
      "project_ids_without_curator_id": [],
      "place_guess": "Chatham County, NC, USA",
      "identifications": [
        {
          "id": 453113577,
          "uuid": "aad6cf6e-ca59-4cc4-9786-bdbcdc3de8a2",
          "user": {
            "id": 7637579,
            "login": "ywcai",
            "spam": false,
            "suspended": false,
            "created_at": "2023-11-27T05:26:48+00:00",
            "login_autocomplete": "ywcai",
            "login_exact": "ywcai",
            "name": null,
            "name_autocomplete": null,
            "orcid": null,
            "icon": "https://static.inaturalist.org/attachments/users/icons/7637579/thumb.png?1709243941",
            "observations_count": 28,
            "identifications_count": 0,
            "journal_posts_count": 0,
            "activity_count": 28,
            "species_count": 28,
            "universal_search_rank": 28,
            "roles": [],
            "site_id": 1,
            "icon_url": "https://static.inaturalist.org/attachments/users/icons/7637579/medium.png?1709243941"
          },
          "created_at": "2024-02-20T20:09:31+00:00",
          "created_at_details": {
            "date": "2024-02-20",
            "day": 20,
            "month": 2,
            "year": 2024,
            "hour": 20,
            "week": 8
          },
          "body": null,
          "category": "improving",
          "current": true,
          "flags": [],
          "own_observation": true,
          "taxon_change": null,
          "vision": true,
          "disagreement": null,
          "previous_observation_taxon_id": 116999,
          "spam": false,
          "taxon_id": 116999,
          "hidden": false,
          "moderator_actions": [],
          "taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey",
            "ancestors": [
              {
                "id": 1,
                "rank": "kingdom",
                "rank_level": 70,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1],
                "is_active": true,
                "name": "Animalia",
                "parent_id": 48460,
                "ancestry": "48460",
                "extinct": false,
                "default_photo": {
                  "id": 80678745,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/medium.jpg"
                },
                "taxon_changes_count": 8,
                "taxon_schemes_count": 2,
                "observations_count": 96818147,
                "flag_counts": { "resolved": 15, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": null,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Animal",
                "complete_rank": "order",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Animals"
              },
              {
                "id": 2,
                "rank": "phylum",
                "rank_level": 60,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2],
                "is_active": true,
                "name": "Chordata",
                "parent_id": 1,
                "ancestry": "48460/1",
                "extinct": false,
                "default_photo": {
                  "id": 80551845,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 2,
                "observations_count": 39396172,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 77563,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Chordate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Chordates"
              },
              {
                "id": 355675,
                "rank": "subphylum",
                "rank_level": 57,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2, 355675],
                "is_active": true,
                "name": "Vertebrata",
                "parent_id": 2,
                "ancestry": "48460/1/2",
                "extinct": false,
                "default_photo": {
                  "id": 80551642,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/medium.jpg"
                },
                "taxon_changes_count": 1,
                "taxon_schemes_count": 1,
                "observations_count": 39326163,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 74444,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Vertebrate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Vertebrates"
              },
              {
                "id": 3,
                "rank": "class",
                "rank_level": 50,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3],
                "is_active": true,
                "name": "Aves",
                "parent_id": 355675,
                "ancestry": "48460/1/2/355675",
                "extinct": false,
                "default_photo": {
                  "id": 2967053,
                  "license_code": "cc-by-nc",
                  "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "original_dimensions": { "height": 1333, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/medium.jpg"
                },
                "taxon_changes_count": 4,
                "taxon_schemes_count": 2,
                "observations_count": 26382125,
                "flag_counts": { "resolved": 16, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 10852,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Bird",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Birds"
              },
              {
                "id": 71261,
                "rank": "order",
                "rank_level": 40,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261],
                "is_active": true,
                "name": "Accipitriformes",
                "parent_id": 3,
                "ancestry": "48460/1/2/355675/3",
                "extinct": false,
                "default_photo": {
                  "id": 9972001,
                  "license_code": "cc-by",
                  "attribution": "(c) Jacob Spinks, some rights reserved (CC BY)",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "original_dimensions": { "height": 1200, "width": 1500 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 1410978,
                "flag_counts": { "resolved": 1, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 251,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Accipitriformes",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Hawks, Eagles, Kites, and Allies"
              },
              {
                "id": 200958,
                "rank": "family",
                "rank_level": 30,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958],
                "is_active": true,
                "name": "Pandionidae",
                "parent_id": 71261,
                "ancestry": "48460/1/2/355675/3/71261",
                "extinct": false,
                "default_photo": {
                  "id": 31658015,
                  "license_code": null,
                  "attribution": "(c) nickmandalou, all rights reserved",
                  "url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "original_dimensions": { "height": 1353, "width": 2048 },
                  "flags": [],
                  "square_url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "medium_url": "https://static.inaturalist.org/photos/31658015/medium.jpeg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 115231,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Pandion_(bird)",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              },
              {
                "id": 71725,
                "rank": "genus",
                "rank_level": 20,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
                "is_active": true,
                "name": "Pandion",
                "parent_id": 200958,
                "ancestry": "48460/1/2/355675/3/71261/200958",
                "extinct": false,
                "default_photo": {
                  "id": 117402357,
                  "license_code": "cc-by-nc-nd",
                  "attribution": "(c) dplawrance, some rights reserved (CC BY-NC-ND), uploaded by dplawrance",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "original_dimensions": { "height": 1365, "width": 2048 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 114532,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              }
            ]
          },
          "previous_observation_taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [
              48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999
            ],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey"
          }
        },
        {
          "id": 453113801,
          "uuid": "d584ea84-c732-4692-a399-254aa4cf068a",
          "user": {
            "id": 1113591,
            "login": "caseybirds",
            "spam": false,
            "suspended": false,
            "created_at": "2018-07-29T18:41:36+00:00",
            "login_autocomplete": "caseybirds",
            "login_exact": "caseybirds",
            "name": null,
            "name_autocomplete": null,
            "orcid": null,
            "icon": "https://static.inaturalist.org/attachments/users/icons/1113591/thumb.jpg?1658097370",
            "observations_count": 921,
            "identifications_count": 131672,
            "journal_posts_count": 0,
            "activity_count": 132593,
            "species_count": 607,
            "universal_search_rank": 921,
            "roles": [],
            "site_id": 1,
            "icon_url": "https://static.inaturalist.org/attachments/users/icons/1113591/medium.jpg?1658097370"
          },
          "created_at": "2024-02-20T20:10:20+00:00",
          "created_at_details": {
            "date": "2024-02-20",
            "day": 20,
            "month": 2,
            "year": 2024,
            "hour": 20,
            "week": 8
          },
          "body": null,
          "category": "supporting",
          "current": true,
          "flags": [],
          "own_observation": false,
          "taxon_change": null,
          "vision": false,
          "disagreement": false,
          "previous_observation_taxon_id": 116999,
          "spam": false,
          "taxon_id": 116999,
          "hidden": false,
          "moderator_actions": [],
          "taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey",
            "ancestors": [
              {
                "id": 1,
                "rank": "kingdom",
                "rank_level": 70,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1],
                "is_active": true,
                "name": "Animalia",
                "parent_id": 48460,
                "ancestry": "48460",
                "extinct": false,
                "default_photo": {
                  "id": 80678745,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/medium.jpg"
                },
                "taxon_changes_count": 8,
                "taxon_schemes_count": 2,
                "observations_count": 96818147,
                "flag_counts": { "resolved": 15, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": null,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Animal",
                "complete_rank": "order",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Animals"
              },
              {
                "id": 2,
                "rank": "phylum",
                "rank_level": 60,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2],
                "is_active": true,
                "name": "Chordata",
                "parent_id": 1,
                "ancestry": "48460/1",
                "extinct": false,
                "default_photo": {
                  "id": 80551845,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 2,
                "observations_count": 39396172,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 77563,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Chordate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Chordates"
              },
              {
                "id": 355675,
                "rank": "subphylum",
                "rank_level": 57,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2, 355675],
                "is_active": true,
                "name": "Vertebrata",
                "parent_id": 2,
                "ancestry": "48460/1/2",
                "extinct": false,
                "default_photo": {
                  "id": 80551642,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/medium.jpg"
                },
                "taxon_changes_count": 1,
                "taxon_schemes_count": 1,
                "observations_count": 39326163,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 74444,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Vertebrate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Vertebrates"
              },
              {
                "id": 3,
                "rank": "class",
                "rank_level": 50,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3],
                "is_active": true,
                "name": "Aves",
                "parent_id": 355675,
                "ancestry": "48460/1/2/355675",
                "extinct": false,
                "default_photo": {
                  "id": 2967053,
                  "license_code": "cc-by-nc",
                  "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "original_dimensions": { "height": 1333, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/medium.jpg"
                },
                "taxon_changes_count": 4,
                "taxon_schemes_count": 2,
                "observations_count": 26382125,
                "flag_counts": { "resolved": 16, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 10852,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Bird",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Birds"
              },
              {
                "id": 71261,
                "rank": "order",
                "rank_level": 40,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261],
                "is_active": true,
                "name": "Accipitriformes",
                "parent_id": 3,
                "ancestry": "48460/1/2/355675/3",
                "extinct": false,
                "default_photo": {
                  "id": 9972001,
                  "license_code": "cc-by",
                  "attribution": "(c) Jacob Spinks, some rights reserved (CC BY)",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "original_dimensions": { "height": 1200, "width": 1500 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 1410978,
                "flag_counts": { "resolved": 1, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 251,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Accipitriformes",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Hawks, Eagles, Kites, and Allies"
              },
              {
                "id": 200958,
                "rank": "family",
                "rank_level": 30,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958],
                "is_active": true,
                "name": "Pandionidae",
                "parent_id": 71261,
                "ancestry": "48460/1/2/355675/3/71261",
                "extinct": false,
                "default_photo": {
                  "id": 31658015,
                  "license_code": null,
                  "attribution": "(c) nickmandalou, all rights reserved",
                  "url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "original_dimensions": { "height": 1353, "width": 2048 },
                  "flags": [],
                  "square_url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "medium_url": "https://static.inaturalist.org/photos/31658015/medium.jpeg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 115231,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Pandion_(bird)",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              },
              {
                "id": 71725,
                "rank": "genus",
                "rank_level": 20,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
                "is_active": true,
                "name": "Pandion",
                "parent_id": 200958,
                "ancestry": "48460/1/2/355675/3/71261/200958",
                "extinct": false,
                "default_photo": {
                  "id": 117402357,
                  "license_code": "cc-by-nc-nd",
                  "attribution": "(c) dplawrance, some rights reserved (CC BY-NC-ND), uploaded by dplawrance",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "original_dimensions": { "height": 1365, "width": 2048 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 114532,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              }
            ]
          },
          "previous_observation_taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [
              48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999
            ],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey"
          }
        },
        {
          "id": 453141867,
          "uuid": "5ec65b34-30ea-4c7e-8bb1-bc373edc3264",
          "user": {
            "id": 4072918,
            "login": "hawkparty",
            "spam": false,
            "suspended": false,
            "created_at": "2021-03-06T20:44:35+00:00",
            "login_autocomplete": "hawkparty",
            "login_exact": "hawkparty",
            "name": "Hawk T.",
            "name_autocomplete": "Hawk T.",
            "orcid": null,
            "icon": "https://static.inaturalist.org/attachments/users/icons/4072918/thumb.jpeg?1615064267",
            "observations_count": 28541,
            "identifications_count": 73788,
            "journal_posts_count": 0,
            "activity_count": 102329,
            "species_count": 1388,
            "universal_search_rank": 28541,
            "roles": ["curator"],
            "site_id": 1,
            "icon_url": "https://static.inaturalist.org/attachments/users/icons/4072918/medium.jpeg?1615064267"
          },
          "created_at": "2024-02-20T22:00:15+00:00",
          "created_at_details": {
            "date": "2024-02-20",
            "day": 20,
            "month": 2,
            "year": 2024,
            "hour": 22,
            "week": 8
          },
          "body": null,
          "category": "supporting",
          "current": true,
          "flags": [],
          "own_observation": false,
          "taxon_change": null,
          "vision": false,
          "disagreement": false,
          "previous_observation_taxon_id": 116999,
          "spam": false,
          "taxon_id": 116999,
          "hidden": false,
          "moderator_actions": [],
          "taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey",
            "ancestors": [
              {
                "id": 1,
                "rank": "kingdom",
                "rank_level": 70,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1],
                "is_active": true,
                "name": "Animalia",
                "parent_id": 48460,
                "ancestry": "48460",
                "extinct": false,
                "default_photo": {
                  "id": 80678745,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/medium.jpg"
                },
                "taxon_changes_count": 8,
                "taxon_schemes_count": 2,
                "observations_count": 96818147,
                "flag_counts": { "resolved": 15, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": null,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Animal",
                "complete_rank": "order",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Animals"
              },
              {
                "id": 2,
                "rank": "phylum",
                "rank_level": 60,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2],
                "is_active": true,
                "name": "Chordata",
                "parent_id": 1,
                "ancestry": "48460/1",
                "extinct": false,
                "default_photo": {
                  "id": 80551845,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 2,
                "observations_count": 39396172,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 77563,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Chordate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Chordates"
              },
              {
                "id": 355675,
                "rank": "subphylum",
                "rank_level": 57,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2, 355675],
                "is_active": true,
                "name": "Vertebrata",
                "parent_id": 2,
                "ancestry": "48460/1/2",
                "extinct": false,
                "default_photo": {
                  "id": 80551642,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/medium.jpg"
                },
                "taxon_changes_count": 1,
                "taxon_schemes_count": 1,
                "observations_count": 39326163,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 74444,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Vertebrate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Vertebrates"
              },
              {
                "id": 3,
                "rank": "class",
                "rank_level": 50,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3],
                "is_active": true,
                "name": "Aves",
                "parent_id": 355675,
                "ancestry": "48460/1/2/355675",
                "extinct": false,
                "default_photo": {
                  "id": 2967053,
                  "license_code": "cc-by-nc",
                  "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "original_dimensions": { "height": 1333, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/medium.jpg"
                },
                "taxon_changes_count": 4,
                "taxon_schemes_count": 2,
                "observations_count": 26382125,
                "flag_counts": { "resolved": 16, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 10852,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Bird",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Birds"
              },
              {
                "id": 71261,
                "rank": "order",
                "rank_level": 40,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261],
                "is_active": true,
                "name": "Accipitriformes",
                "parent_id": 3,
                "ancestry": "48460/1/2/355675/3",
                "extinct": false,
                "default_photo": {
                  "id": 9972001,
                  "license_code": "cc-by",
                  "attribution": "(c) Jacob Spinks, some rights reserved (CC BY)",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "original_dimensions": { "height": 1200, "width": 1500 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 1410978,
                "flag_counts": { "resolved": 1, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 251,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Accipitriformes",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Hawks, Eagles, Kites, and Allies"
              },
              {
                "id": 200958,
                "rank": "family",
                "rank_level": 30,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958],
                "is_active": true,
                "name": "Pandionidae",
                "parent_id": 71261,
                "ancestry": "48460/1/2/355675/3/71261",
                "extinct": false,
                "default_photo": {
                  "id": 31658015,
                  "license_code": null,
                  "attribution": "(c) nickmandalou, all rights reserved",
                  "url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "original_dimensions": { "height": 1353, "width": 2048 },
                  "flags": [],
                  "square_url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "medium_url": "https://static.inaturalist.org/photos/31658015/medium.jpeg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 115231,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Pandion_(bird)",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              },
              {
                "id": 71725,
                "rank": "genus",
                "rank_level": 20,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
                "is_active": true,
                "name": "Pandion",
                "parent_id": 200958,
                "ancestry": "48460/1/2/355675/3/71261/200958",
                "extinct": false,
                "default_photo": {
                  "id": 117402357,
                  "license_code": "cc-by-nc-nd",
                  "attribution": "(c) dplawrance, some rights reserved (CC BY-NC-ND), uploaded by dplawrance",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "original_dimensions": { "height": 1365, "width": 2048 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 114532,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              }
            ]
          },
          "previous_observation_taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [
              48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999
            ],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey"
          }
        }
      ],
      "project_observations": [],
      "observation_photos": [
        {
          "id": 328390211,
          "position": 0,
          "uuid": "f3f78cd9-8090-468f-b4c5-48fa92a1abc9",
          "photo_id": 352636609,
          "photo": {
            "id": 352636609,
            "license_code": "cc-by-nc",
            "original_dimensions": { "width": 1536, "height": 2048 },
            "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/352636609/square.jpg",
            "attribution": "(c) ywcai, some rights reserved (CC BY-NC)",
            "flags": [],
            "moderator_actions": [],
            "hidden": false
          }
        }
      ],
      "photos": [
        {
          "id": 352636609,
          "license_code": "cc-by-nc",
          "original_dimensions": { "width": 1536, "height": 2048 },
          "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/352636609/square.jpg",
          "attribution": "(c) ywcai, some rights reserved (CC BY-NC)",
          "flags": [],
          "moderator_actions": [],
          "hidden": false
        }
      ],
      "faves": [],
      "non_owner_ids": [
        {
          "id": 453113801,
          "uuid": "d584ea84-c732-4692-a399-254aa4cf068a",
          "user": {
            "id": 1113591,
            "login": "caseybirds",
            "spam": false,
            "suspended": false,
            "created_at": "2018-07-29T18:41:36+00:00",
            "login_autocomplete": "caseybirds",
            "login_exact": "caseybirds",
            "name": null,
            "name_autocomplete": null,
            "orcid": null,
            "icon": "https://static.inaturalist.org/attachments/users/icons/1113591/thumb.jpg?1658097370",
            "observations_count": 921,
            "identifications_count": 131672,
            "journal_posts_count": 0,
            "activity_count": 132593,
            "species_count": 607,
            "universal_search_rank": 921,
            "roles": [],
            "site_id": 1,
            "icon_url": "https://static.inaturalist.org/attachments/users/icons/1113591/medium.jpg?1658097370"
          },
          "created_at": "2024-02-20T20:10:20+00:00",
          "created_at_details": {
            "date": "2024-02-20",
            "day": 20,
            "month": 2,
            "year": 2024,
            "hour": 20,
            "week": 8
          },
          "body": null,
          "category": "supporting",
          "current": true,
          "flags": [],
          "own_observation": false,
          "taxon_change": null,
          "vision": false,
          "disagreement": false,
          "previous_observation_taxon_id": 116999,
          "spam": false,
          "taxon_id": 116999,
          "hidden": false,
          "moderator_actions": [],
          "taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey",
            "ancestors": [
              {
                "id": 1,
                "rank": "kingdom",
                "rank_level": 70,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1],
                "is_active": true,
                "name": "Animalia",
                "parent_id": 48460,
                "ancestry": "48460",
                "extinct": false,
                "default_photo": {
                  "id": 80678745,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/medium.jpg"
                },
                "taxon_changes_count": 8,
                "taxon_schemes_count": 2,
                "observations_count": 96818147,
                "flag_counts": { "resolved": 15, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": null,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Animal",
                "complete_rank": "order",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Animals"
              },
              {
                "id": 2,
                "rank": "phylum",
                "rank_level": 60,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2],
                "is_active": true,
                "name": "Chordata",
                "parent_id": 1,
                "ancestry": "48460/1",
                "extinct": false,
                "default_photo": {
                  "id": 80551845,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 2,
                "observations_count": 39396172,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 77563,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Chordate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Chordates"
              },
              {
                "id": 355675,
                "rank": "subphylum",
                "rank_level": 57,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2, 355675],
                "is_active": true,
                "name": "Vertebrata",
                "parent_id": 2,
                "ancestry": "48460/1/2",
                "extinct": false,
                "default_photo": {
                  "id": 80551642,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/medium.jpg"
                },
                "taxon_changes_count": 1,
                "taxon_schemes_count": 1,
                "observations_count": 39326163,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 74444,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Vertebrate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Vertebrates"
              },
              {
                "id": 3,
                "rank": "class",
                "rank_level": 50,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3],
                "is_active": true,
                "name": "Aves",
                "parent_id": 355675,
                "ancestry": "48460/1/2/355675",
                "extinct": false,
                "default_photo": {
                  "id": 2967053,
                  "license_code": "cc-by-nc",
                  "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "original_dimensions": { "height": 1333, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/medium.jpg"
                },
                "taxon_changes_count": 4,
                "taxon_schemes_count": 2,
                "observations_count": 26382125,
                "flag_counts": { "resolved": 16, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 10852,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Bird",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Birds"
              },
              {
                "id": 71261,
                "rank": "order",
                "rank_level": 40,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261],
                "is_active": true,
                "name": "Accipitriformes",
                "parent_id": 3,
                "ancestry": "48460/1/2/355675/3",
                "extinct": false,
                "default_photo": {
                  "id": 9972001,
                  "license_code": "cc-by",
                  "attribution": "(c) Jacob Spinks, some rights reserved (CC BY)",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "original_dimensions": { "height": 1200, "width": 1500 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 1410978,
                "flag_counts": { "resolved": 1, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 251,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Accipitriformes",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Hawks, Eagles, Kites, and Allies"
              },
              {
                "id": 200958,
                "rank": "family",
                "rank_level": 30,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958],
                "is_active": true,
                "name": "Pandionidae",
                "parent_id": 71261,
                "ancestry": "48460/1/2/355675/3/71261",
                "extinct": false,
                "default_photo": {
                  "id": 31658015,
                  "license_code": null,
                  "attribution": "(c) nickmandalou, all rights reserved",
                  "url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "original_dimensions": { "height": 1353, "width": 2048 },
                  "flags": [],
                  "square_url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "medium_url": "https://static.inaturalist.org/photos/31658015/medium.jpeg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 115231,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Pandion_(bird)",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              },
              {
                "id": 71725,
                "rank": "genus",
                "rank_level": 20,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
                "is_active": true,
                "name": "Pandion",
                "parent_id": 200958,
                "ancestry": "48460/1/2/355675/3/71261/200958",
                "extinct": false,
                "default_photo": {
                  "id": 117402357,
                  "license_code": "cc-by-nc-nd",
                  "attribution": "(c) dplawrance, some rights reserved (CC BY-NC-ND), uploaded by dplawrance",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "original_dimensions": { "height": 1365, "width": 2048 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 114532,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              }
            ]
          },
          "previous_observation_taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [
              48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999
            ],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey"
          }
        },
        {
          "id": 453141867,
          "uuid": "5ec65b34-30ea-4c7e-8bb1-bc373edc3264",
          "user": {
            "id": 4072918,
            "login": "hawkparty",
            "spam": false,
            "suspended": false,
            "created_at": "2021-03-06T20:44:35+00:00",
            "login_autocomplete": "hawkparty",
            "login_exact": "hawkparty",
            "name": "Hawk T.",
            "name_autocomplete": "Hawk T.",
            "orcid": null,
            "icon": "https://static.inaturalist.org/attachments/users/icons/4072918/thumb.jpeg?1615064267",
            "observations_count": 28541,
            "identifications_count": 73788,
            "journal_posts_count": 0,
            "activity_count": 102329,
            "species_count": 1388,
            "universal_search_rank": 28541,
            "roles": ["curator"],
            "site_id": 1,
            "icon_url": "https://static.inaturalist.org/attachments/users/icons/4072918/medium.jpeg?1615064267"
          },
          "created_at": "2024-02-20T22:00:15+00:00",
          "created_at_details": {
            "date": "2024-02-20",
            "day": 20,
            "month": 2,
            "year": 2024,
            "hour": 22,
            "week": 8
          },
          "body": null,
          "category": "supporting",
          "current": true,
          "flags": [],
          "own_observation": false,
          "taxon_change": null,
          "vision": false,
          "disagreement": false,
          "previous_observation_taxon_id": 116999,
          "spam": false,
          "taxon_id": 116999,
          "hidden": false,
          "moderator_actions": [],
          "taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey",
            "ancestors": [
              {
                "id": 1,
                "rank": "kingdom",
                "rank_level": 70,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1],
                "is_active": true,
                "name": "Animalia",
                "parent_id": 48460,
                "ancestry": "48460",
                "extinct": false,
                "default_photo": {
                  "id": 80678745,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80678745/medium.jpg"
                },
                "taxon_changes_count": 8,
                "taxon_schemes_count": 2,
                "observations_count": 96818147,
                "flag_counts": { "resolved": 15, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": null,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Animal",
                "complete_rank": "order",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Animals"
              },
              {
                "id": 2,
                "rank": "phylum",
                "rank_level": 60,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2],
                "is_active": true,
                "name": "Chordata",
                "parent_id": 1,
                "ancestry": "48460/1",
                "extinct": false,
                "default_photo": {
                  "id": 80551845,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551845/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 2,
                "observations_count": 39396172,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 77563,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Chordate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Chordates"
              },
              {
                "id": 355675,
                "rank": "subphylum",
                "rank_level": 57,
                "iconic_taxon_id": 1,
                "ancestor_ids": [48460, 1, 2, 355675],
                "is_active": true,
                "name": "Vertebrata",
                "parent_id": 2,
                "ancestry": "48460/1/2",
                "extinct": false,
                "default_photo": {
                  "id": 80551642,
                  "license_code": "cc0",
                  "attribution": "no rights reserved, uploaded by Abhas Misraraj",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "original_dimensions": { "height": 2000, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/80551642/medium.jpg"
                },
                "taxon_changes_count": 1,
                "taxon_schemes_count": 1,
                "observations_count": 39326163,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 74444,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Vertebrate",
                "complete_rank": "species",
                "iconic_taxon_name": "Animalia",
                "preferred_common_name": "Vertebrates"
              },
              {
                "id": 3,
                "rank": "class",
                "rank_level": 50,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3],
                "is_active": true,
                "name": "Aves",
                "parent_id": 355675,
                "ancestry": "48460/1/2/355675",
                "extinct": false,
                "default_photo": {
                  "id": 2967053,
                  "license_code": "cc-by-nc",
                  "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "original_dimensions": { "height": 1333, "width": 2000 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/2967053/medium.jpg"
                },
                "taxon_changes_count": 4,
                "taxon_schemes_count": 2,
                "observations_count": 26382125,
                "flag_counts": { "resolved": 16, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 10852,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Bird",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Birds"
              },
              {
                "id": 71261,
                "rank": "order",
                "rank_level": 40,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261],
                "is_active": true,
                "name": "Accipitriformes",
                "parent_id": 3,
                "ancestry": "48460/1/2/355675/3",
                "extinct": false,
                "default_photo": {
                  "id": 9972001,
                  "license_code": "cc-by",
                  "attribution": "(c) Jacob Spinks, some rights reserved (CC BY)",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "original_dimensions": { "height": 1200, "width": 1500 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/9972001/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 1410978,
                "flag_counts": { "resolved": 1, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 251,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Accipitriformes",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Hawks, Eagles, Kites, and Allies"
              },
              {
                "id": 200958,
                "rank": "family",
                "rank_level": 30,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958],
                "is_active": true,
                "name": "Pandionidae",
                "parent_id": 71261,
                "ancestry": "48460/1/2/355675/3/71261",
                "extinct": false,
                "default_photo": {
                  "id": 31658015,
                  "license_code": null,
                  "attribution": "(c) nickmandalou, all rights reserved",
                  "url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "original_dimensions": { "height": 1353, "width": 2048 },
                  "flags": [],
                  "square_url": "https://static.inaturalist.org/photos/31658015/square.jpeg",
                  "medium_url": "https://static.inaturalist.org/photos/31658015/medium.jpeg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 115231,
                "flag_counts": { "resolved": 2, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Pandion_(bird)",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              },
              {
                "id": 71725,
                "rank": "genus",
                "rank_level": 20,
                "iconic_taxon_id": 3,
                "ancestor_ids": [48460, 1, 2, 355675, 3, 71261, 200958, 71725],
                "is_active": true,
                "name": "Pandion",
                "parent_id": 200958,
                "ancestry": "48460/1/2/355675/3/71261/200958",
                "extinct": false,
                "default_photo": {
                  "id": 117402357,
                  "license_code": "cc-by-nc-nd",
                  "attribution": "(c) dplawrance, some rights reserved (CC BY-NC-ND), uploaded by dplawrance",
                  "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "original_dimensions": { "height": 1365, "width": 2048 },
                  "flags": [],
                  "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/square.jpg",
                  "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/117402357/medium.jpg"
                },
                "taxon_changes_count": 0,
                "taxon_schemes_count": 1,
                "observations_count": 114532,
                "flag_counts": { "resolved": 0, "unresolved": 0 },
                "current_synonymous_taxon_ids": null,
                "atlas_id": null,
                "complete_species_count": 1,
                "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
                "complete_rank": "subspecies",
                "iconic_taxon_name": "Aves",
                "preferred_common_name": "Ospreys"
              }
            ]
          },
          "previous_observation_taxon": {
            "id": 116999,
            "rank": "species",
            "rank_level": 10,
            "iconic_taxon_id": 3,
            "ancestor_ids": [
              48460, 1, 2, 355675, 3, 71261, 200958, 71725, 116999
            ],
            "is_active": true,
            "min_species_taxon_id": 116999,
            "name": "Pandion haliaetus",
            "parent_id": 71725,
            "ancestry": "48460/1/2/355675/3/71261/200958/71725",
            "min_species_ancestry": "48460,1,2,355675,3,71261,200958,71725,116999",
            "extinct": false,
            "created_at": "2011-08-10T18:24:12+00:00",
            "default_photo": {
              "id": 6903515,
              "license_code": "cc-by-nc",
              "attribution": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
              "url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "original_dimensions": { "height": 1366, "width": 2048 },
              "flags": [],
              "square_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/square.jpg",
              "medium_url": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg"
            },
            "taxon_changes_count": 0,
            "taxon_schemes_count": 9,
            "observations_count": 114414,
            "photos_locked": false,
            "universal_search_rank": 114414,
            "flag_counts": { "resolved": 4, "unresolved": 0 },
            "current_synonymous_taxon_ids": null,
            "atlas_id": null,
            "complete_species_count": null,
            "wikipedia_url": "http://en.wikipedia.org/wiki/Osprey",
            "complete_rank": "subspecies",
            "iconic_taxon_name": "Aves",
            "preferred_common_name": "Osprey"
          }
        }
      ]
    },
        '''
        super().__init__(
            name="cq_inaturalist_observations",
            title="iNaturalist Observations",
            columns=[
                Column("id", pa.uint64(), primary_key=True),
                Column("quality_grade", pa.string()),
                Column("uuid", pa.string()),
                Column("time_observed_at", pa.string()),
                Column("taxon_geoprivacy", pa.string()),
                Column("identifications_most_agree", pa.bool_()),
                Column("species_guess", pa.string()),
                Column("identifications_most_disagree", pa.bool_()),
                Column("positional_accuracy", pa.uint32()),
                Column("observed_on", pa.string()),
                Column("observed_on_string", pa.string()),
                Column("taxon", JSONType()),
                Column("uri", pa.string()),
                Column("location", pa.string()),
                Column("identifications_some_agree", pa.bool_()),
                Column("num_identification_agreements", pa.uint16()),
                Column("num_identification_disagreements", pa.uint16()),
                Column("place_guess", pa.string()),
                Column("identifications", JSONType()),
                Column("annotations", JSONType()),
                Column("photos", JSONType()),
            ],
        )

    @property
    def resolver(self):
        return ObservationResolver(table=self)


class ObservationResolver(TableResolver):
    def __init__(self, table) -> None:
        super().__init__(table=table)

    def resolve(
        self, client: Client, parent_resource: Resource
    ) -> Generator[Any, None, None]:
        for observation_response in client.client.observation_iterator():
            yield observation_response
