select
    data.id as taxon_id,
    data.rank,
    data.name,
    data.native,
    data.endemic,
    data.extinct,
    data.ancestry,
    data.atlas_id,
    data.is_active,
    data.parent_id,
    data.created_at,
    data.introduced,
    data.rank_level,
    data.threatened,
    data.complete_rank,
    data.photos_locked,
    data.wikipedia_url,
    data.iconic_taxon_id,
    data.iconic_taxon_name,
    data.observations_count,
    data.taxon_changes_count,
    data.taxon_schemes_count,
    data.min_species_ancestry,
    data.min_species_taxon_id,
    data.preferred_common_name,
    data.universal_search_rank,
    data.complete_species_count,
    data.current_synonymous_taxon_ids
from
    {{ ref("stg_taxon") }},
    jsonb_to_record(taxon) as data(
        id int,
        rank text,
        name text,
        native boolean,
        endemic boolean,
        extinct boolean,
        ancestry text,
        atlas_id int,
        is_active boolean,
        parent_id int,
        created_at text,
        introduced boolean,
        rank_level int,
        threatened boolean,
        complete_rank text,
        photos_locked boolean,
        wikipedia_url text,
        iconic_taxon_id int,
        iconic_taxon_name text,
        observations_count int,
        taxon_changes_count int,
        taxon_schemes_count int,
        min_species_ancestry text,
        min_species_taxon_id int,
        preferred_common_name text,
        universal_search_rank int,
        complete_species_count int,
        current_synonymous_taxon_ids int
    )
